-- =====================================================================
-- ESPACE COACHING - referentiel du questionnaire
-- GENERE PAR outils/extraire-cle.mjs. Ne pas modifier a la main.
-- Source : Enneagramme Preparation Mentale.xlsx, support de l'Academie.
-- A rejouer apres 0001_pm_socle.sql, et a chaque correction du classeur.
-- =====================================================================

insert into public.pm_types (numero, nom) values
  (1, 'Perfectionniste'),
  (2, 'Aidant'),
  (3, 'Compétiteur'),
  (4, 'Artiste'),
  (5, 'Penseur'),
  (6, 'Loyaliste'),
  (7, 'Jouisseur'),
  (8, 'Leader'),
  (9, 'Médiateur')
on conflict (numero) do update set nom = excluded.nom;

insert into public.pm_items (numero, type, texte) values
  (1, 8, 'Je passe pour une personne solide et suscite assez rapidement le respect quand je m’affirme en société.'),
  (2, 9, 'Face à des situations de tension, de conflit ou d''agressivité, je garde facilement mon calme et considère ma stabilité émotionnelle comme un atout pour prendre du recul avant de m''exprimer.'),
  (3, 1, 'Si je repère des erreurs, je me sens le devoir d’intervenir rapidement pour corriger les choses car tous les détails comptent si on veut améliorer les choses pour progresser.'),
  (4, 2, 'Je me sens plutôt bien quand je suis au service des autres, quitte parfois à sacrifier facilement mon temps, mon énergie ou même mon argent, pour les soutenir face à leurs difficultés.'),
  (5, 3, 'J’aime mobiliser de l’énergie dans une action particulière, surtout si celle-ci contribue à mon succès et/ou à ma reconnaissance personnelle, sociale ou professionnelle'),
  (6, 4, 'Enfant, je me sentais déjà très différent(e) des autres et j’avais le sentiment de déranger.'),
  (7, 5, 'Je tiens particulièrement à préserver ma vie privée et avoir du temps pour moi, pour me retrouver et prendre le recul dont j’ai besoin quand c’est nécessaire.'),
  (8, 6, 'Quand j’ai des décisions importantes à prendre, je demande l’avis des autres, car j’ai parfois peur de faire une bêtise.'),
  (9, 7, 'Afin de préserver un maximum d’opportunités intéressantes, je peux me sentir vite frustré(e) si l’on m’impose des règles qui à mes yeux n’ont pas lieu d’être.'),
  (10, 9, 'Même en cas de tension relationnelle, je sais préserver un sentiment d’union et d’harmonie, car j’estime que c’est la meilleure chose qui soit pour apaiser les esprits et préserver le lien.'),
  (11, 1, 'J’aime que les choses soient parfaites et je suis dérangé(e) par les imperfections à commencer par ce que les gens peuvent percevoir chez moi.'),
  (12, 2, 'Je peux consacrer facilement du temps libre pour soutenir des personnes qui en ont besoin et trouve cela gratifiant de sentir que ma présence est utile pour eux.'),
  (13, 3, 'Je suis vigilant(e) au fait de préserver une image plutôt brillante vis-à-vis de ma carrière et de mon style de vie en générale.'),
  (14, 4, 'Je peux être enclin à me replonger émotionnellement dans des souvenirs, ce qui peut donner l’impression que je ressasse toujours les mêmes histoires'),
  (15, 5, 'Je fonctionne d’une façon plutôt objective et j’aime réfléchir par moi-même pour résoudre des problèmes avant ou après en avoir discuté avec les autres.'),
  (16, 6, 'Pour me sentir bien dans une équipe, j’aime solliciter l’avis de chacun afin de privilégier la cohésion du groupe dans son ensemble.'),
  (17, 7, 'Je suis toujours partant(e) quand il s’agit de se faire plaisir et de profiter pleinement de la vie.'),
  (18, 8, 'Au besoin, je reprends vite la main sur les décisions à prendre, quitte à imposer parfois mon point de vue, quels que soient les avis ou sensibilités exprimés'),
  (19, 1, 'Je peux être facilement critique avec moi-même, mais aussi avec les autres, par soucis d’exigence et de perfection.'),
  (20, 2, 'Je suis de nature affectueuse et parfois même très protecteur(trice), voire possessif(ve) avec les gens que j’aime et que j’affectionne.'),
  (21, 3, 'Je tiens à préserver une bonne image concernant ma posture, car je considère que ce que l’on perçoit de moi, conditionne le succès auquel j’aspire et la reconnaissance que je souhaite.'),
  (22, 4, 'Ma sensibilité, une aide précieuse pour mobiliser mon imagination et ma créativité, notamment pour résoudre de nombreux problèmes dans ma vie.'),
  (23, 5, 'J’aime prendre le temps d’analyser les choses tranquillement avant de me précipiter dans une prise de décision.'),
  (24, 6, 'Je peux vite me sentir anxieux(se) ou imprudent(e) si je dois prendre d’importantes décisions sans l’avis des autres.'),
  (25, 7, 'Je peux parfois faire abstraction de quelques règles importantes, si cela me permet de vivre des situations plus excitantes.'),
  (26, 8, 'J’ai confiance en ma force et en mon courage, lorsqu’arrive le moment de prendre une décision, je ne fais pas de compromis.'),
  (27, 9, 'Quitte à prendre sur moi, je suis capable de beaucoup de patience pour éviter les discussions houleuses, les confrontations ou les conflits'),
  (28, 8, 'Je me positionne en négociateur(trice) assez ferme, car je sais imposer mes idées et reprendre le contrôle d’une situation pour en sortir gagnant.'),
  (29, 3, 'Je suis perçu(e) par mon entourage comme ambitieux(se) et très mobilisé(e) pour réussir mes objectifs dès que possible.'),
  (30, 7, 'J’aime me lancer dans de nouvelles aventures ou projets stimulants, même si les situations en cours ne sont pas encore vraiment terminées.'),
  (31, 4, 'J’ai souvent l’impression que personne ne peut me comprendre car il m’est impossible d’expliquer mon fonctionnement et ce sentiment intense d’être différent(e).'),
  (32, 9, 'Par soucis de paix d''esprit et de tranquillité, j’ai parfois tendance à me voiler la face, en laissant trainer des situations importantes à régler, pour plus tard.'),
  (33, 5, 'Je préfère me tenir à l’écart, voire me retirer discrètement de l’agitation, plutôt que de me retrouver pris dans des conversations plus émotionnelles, voire superficielles.'),
  (34, 2, 'J’aime tenir une place de choix dans la vie de mon entourage, savoir qu’ils peuvent compter sur moi en cas de besoin est essentiel pour mon bien-être.'),
  (35, 1, 'Afin d’éviter toutes critiques négatives, je peux donner beaucoup de moi-même et obtenir facilement l’admiration des autres pour l’efficacité de mon travail.'),
  (36, 6, 'Je suis facilement préoccupé(e) ou inquiet(e) par une chose ou une autre qui, pourrait nuire au bien-être de mes proches, concernant ma famille, mes équipes ou mon organisation.'),
  (37, 9, 'Enfant, j’avais le sentiment d’avoir rarement été vu(e) ou entendu(e).'),
  (38, 4, 'J’aime vivre les choses avec intensité et passion, que je peux provoquer avec n’importe quel petit déclencheur'),
  (39, 5, 'J’aime apprendre des autres plus que me révéler moi même, sauf si vous me sollicitez sur mon expertise.'),
  (40, 6, 'J’appréhende facilement qu’une chose grave pourrait m’arriver ou arriver à mes proches.'),
  (41, 1, 'Je suis attentif(ve) au fait d’être bon(ne), fiable, efficace et m’efforce de respecter la parole donnée.'),
  (42, 2, 'La solitude déclenche en moi une forte anxiété car j’ai souvent du mal à définir mes propres besoins.'),
  (43, 3, 'Si face à l’adversité, mon plan ne fonctionne pas, je ne tarde pas à changer (parfois un peu rapidement), de stratégie pour trouver les moyens de progresser autrement vers l’attente de mes objectifs.'),
  (44, 7, 'J’ai une telle tendance à voir le côté positif des choses, que je passe parfois pour une personne irresponsable et coupée de certaines réalités. En faite, je veux juste profiter de cette vie'),
  (45, 8, 'Je suis capable de déployer beaucoup d’énergie pour une personne de mon clan.'),
  (46, 1, 'Je sais ce qui est bien de faire, et j’aime quand les autres s’attachent davantage à peaufiner leurs taches pour parvenir à exprimer leur excellence.'),
  (47, 2, 'Parfois mon souci des autres, me donne envie de les aider par tous les moyens dont je dispose.'),
  (48, 6, '. Enfant, pour éviter le rejet, je me « sur adaptais » à l’autorité de certains leaders pour éviter de me retrouver seul(e).'),
  (49, 8, 'Je suis exigent(e) vis à vis de mes attentes et m’affirme d’une manière simple et directe, quitte à bousculer mon entourage si nécessaire.'),
  (50, 7, 'Je suis surpris(e) parfois par la faculté des gens à voir le mauvais côté des choses, alors que ce serait tellement plus simple et plus constructif de mettre l’accent sur ce qui est positif.'),
  (51, 3, 'Je suis capable de me motiver tout(e) seul(e) et je ne lâche pas facilement lorsque je poursuis un objectif important pour moi.'),
  (52, 4, 'Je suis souvent absorbé(e) par ce que je vis intérieurement et je me sens parfois envieux(se) voire malheureux(se) de ce qu’ont les autres et de ce qui manque à ma vie'),
  (53, 5, 'Lorsque je suis interpelé(e) sur mes ressentis personnels, je ne suis parfois pas très à mon aise, je pense que mes sentiments ne regardent que moi et ne sont pas très utiles pour avancer dans la vie.'),
  (54, 9, 'Il est facile pour moi de m’abandonner dans les propos des autres afin de privilégier un climat de bonne entente tout en restant relax, quels que soient les opinions de chacun.'),
  (55, 5, 'Quand il s’agit de réfléchir sur des projets qui me stimulent, je préfère le faire seul(e), car j’ai l’impression d’avancer plus rapidement dans mon analyse des choses, quitte ensuite à en parler avec d’autres personnes.'),
  (56, 3, 'Je suis de nature ambitieux(se), j’aime apprendre et je suis capable de mobiliser beaucoup d’énergie pour progresser vers une réussite de plus en plus conséquente, pour moi et pour les autres'),
  (57, 1, 'On peut me reprocher mon manque de compassion à l’égard des autres ou de moi-même car je ne peux m’empêcher de relever les imperfections.'),
  (58, 4, 'Mes sentiments et mes goûts raffinés, pour certains détails autour de moi, sont parfois ressentis comme excessifs et/ou hors du commun.'),
  (59, 6, 'Je me sens très honoré(e) par l’appartenance que représente pour moi une équipe, une société ou une communauté.'),
  (60, 8, 'Je suis capable d’utiliser la force pour obtenir ce que je veux, qui plus est quand il s’agit de me faire respecter.'),
  (61, 2, 'Ma spécialité pour attirer l’attention est de me conformer à ce que je ressens ou devine chez les autres, je suis très empathique.'),
  (62, 9, 'Je suis parfois complaisant(e) et je donne à croire que j’aime laisser les choses un peu « planer » pour préserver ma paix d’esprit et ma tranquillité.'),
  (63, 7, 'J’ai horreur de tout ce qui se rapproche de près ou de loin à de l’enfermement.'),
  (64, 8, 'Mes principes de justice sont importants, ils me permettent de récupérer le contrôle d’une situation.'),
  (65, 4, 'Je me laisse parfois emporter par ce que je vis en moi, du coup je me replis sur moi-même en remettant tout ce que je vis en question. Cette mélancolie me permet d’être en contact avec mon imaginaire.'),
  (66, 6, 'Afin de me sentir bien dans un groupe, je veille à ce que les choses se passent bien et j’envisage très vite les choses à régler pour préserver le bien-être et la sécurité de chacun.'),
  (67, 7, 'Je préfère mettre mon énergie sur ce que je veux pour moi, plutôt que de me prendre la tête avec les choses qui me font souffrir, l’important est d’avancer et de profiter de l’avenir.'),
  (68, 9, 'J’ai parfois une fâcheuse tendance à privilégier des actions faciles plutôt que de me focaliser sur des tâches importantes à faire maintenant.'),
  (69, 2, 'Je suis de nature généreux(se) et j’aime prendre soin des autres, même si ça me demande parfois de gros efforts ou des sacrifices'),
  (70, 3, 'Je me sens davantage porté(e) par le démarrage de nouveaux projets que par le fait de le mener à bien, notamment dans le long terme.'),
  (71, 1, 'Je suis une personne intègre, j’ai des principes clairs qui guident précisément mes jugements, ma morale et mes valeurs'),
  (72, 5, 'D’une façon générale, j’ai une tendance naturelle à éviter de m’impliquer émotionnellement dans la vie des gens, sauf si leur histoire me donne l’occasion de comprendre davantage qui ils sont.'),
  (73, 2, '. Mes proches me disent parfois que je devrais prendre davantage soin de moi que de me soucier des autres, mais j’ai l’impression de prendre soin de moi en aidant justement les autres.'),
  (74, 7, 'J’ai besoin de croquer la vie, j’aime mes amis et les sources d’excitations que me procure la vie. Je ne veux pas passer à coté d’expériences que j’ai envie de vivre ou des projets enthousiasmants'),
  (75, 9, 'Mon calme légendaire incite mon entourage à me solliciter pour régler des divergences de point de vue ou atténuer des situations de tension.'),
  (76, 5, 'Lorsque j’investis sur un achat, je le fais plutôt à partir d’éléments rationnels analysés que sur un mode plus intuitif ou émotionnel.'),
  (77, 1, 'Je me sens très vite agacé(e) par les choses qui ne sont pas faites de la meilleure façon qui soit, d’où mon côté parfois critique'),
  (78, 3, 'Pour avancer vers mes objectifs, je suis capable de beaucoup de flexibilité avec les autres, de façon à ajuster mes stratégies aux résultats que je vise, en fonction des sensibilités et des situations de chacun.'),
  (79, 4, 'Ma façon de travailler est parfois non conventionnelle, car j’ai besoin de me sentir libre et porté(e) par l’expression d’une profonde authenticité, afin d’exprimer toute ma sensibilité avec classe, quitte à être très différent(e) des gens.'),
  (80, 8, 'J’ai une forte tendance à l’individualisme, j’éprouve un très fort besoin de faire passer sous contrôle tout ce qui ne l’est pas encore.'),
  (81, 6, 'Je ressens une certaine timidité pour oser me confronter à l’autorité d’un leader, alors que pour d’autre, cette posture semble naturelle.'),
  (82, 1, 'Si un objectif est inatteignable, je peux devenir obsessionnel(le) et produire un travail de fourmi, très méticuleux.'),
  (83, 4, 'Je suis parfois envahi(e) par se sentiment que quelque chose manque à ma vie car j’ai souvent l’impression que les autres sont plus heureux et plus épanouis, qu’ils se posent moins de questions.'),
  (84, 7, 'Je me soucis peu des dépenses, j’aime dépenser sans compter quand je le désir et me retrouve régulièrement avec des choses qui au finale ne me servent pas vraiment'),
  (85, 2, 'Mon besoin de me calquer sur l’autre peut me conduire à passer trop de temps dans des activités qui pourtant ne me concernent pas.'),
  (86, 5, 'La capacité que j’ai à me concentrer sur un projet en restant seul(e) sur plusieurs heures, sans avoir besoin de directives ou d’échanges avec l’extérieur, est un atout pour moi dans la réalisation de mes tâches.'),
  (87, 8, 'Je me sens solide et suffisamment « dur(e) à cuire » pour agir avec fermeté, notamment face à des situations d’injustices, subies par des personnes plus faibles que moi.'),
  (88, 3, 'J’ai du talent pour initier de nouveaux projets (parfois trop) et je sais motiver facilement les autres à me suivre dans ces mêmes projets.'),
  (89, 6, 'Je me sens parfois dans une effervescence de choses à faire pour préparer un travail et ressens de l’anxiété à l’égard des enjeux attendus'),
  (90, 9, 'J’ai une apparence de paresse qui cache souvent en réalité une surcharge mentale.'),
  (91, 6, 'Je prends mes responsabilités sociales ou collectives au sérieux et je suis toujours surpris(e) voire choqué(e) de la légèreté qu’ont d’autres à se considérer comme parfois seul au monde.'),
  (92, 9, 'Bien que facile à vivre, je suis une personne qui peux générer de l’agacement car je peux rester longtemps indécis(e) quand il s’agit de faire des choix.'),
  (93, 3, 'J’ai peu de souvenirs de mon enfance chargée en affectivité. Je remplissais juste très bien mon métier d’enfant, avec ce sentiment que plus je faisais de choses, plus j’obtenais de bons résultats, plus mes parents m’aimaient.'),
  (94, 4, 'J’aime creuser en moi pour rejoindre ma pleine authenticité, mon vrai moi en me comparant aux autres, non pour leur ressembler, mais justement pour me démarquer, me différencier.'),
  (95, 7, 'Je suis d’humeur très positive et toujours partant(e) pour des tâches ou des activités multiples surtout quand elles sont stimulantes.'),
  (96, 1, 'Enfant, j’avais toujours peur de ne pas être suffisamment à la hauteur ou assez exigent(e) pour répondre à ce qui m’était demandé.'),
  (97, 5, 'Je suis parfois perçu(e) comme distant(e), ou peu impliqué(e) émotionnellement, voire peu sociable, car je privilégie naturellement la réflexion à l’expression de mes sentiments.'),
  (98, 8, 'Je sais dire non facilement, l’autorité ne m’impressionne pas le moins du monde.'),
  (99, 2, 'Je me sens parfois trop porté(e) par l’élan de mon coeur et j’éprouve des difficultés à me préserver dans certaine situation vis-à-vis des autres.'),
  (100, 1, 'Je suis plutôt efficace avec un idéal élevé concernant la réalisation de mes tâches, quitte à m’y reprendre de nombreuse fois, pour peaufiner les détails.'),
  (101, 8, 'Dans mes interactions avec les autres, j’ai tendance à compter que sur moi quitte à passer parfois pour une personne brusque à la tête dure.'),
  (102, 9, 'En situation de conflit, j’ai du mal à décider tant que je n’ai pas pris en compte la diversité des points de vue de chacun.'),
  (103, 2, 'Parfois je me sens tellement touché(e) par les difficultés des autres que j’ai tendance à m’exposer excessivement sur le plan émotionnellement, alors qu’il serait bon que je prenne un peu de distance.'),
  (104, 4, 'Il m’arrive de m’isoler pour approfondir la découverte de mon monde intérieur, en recherchant la solitude. Cette tendance peut m’entraîner dans un certain marasme intérieur, voire un sentiment de déprime.'),
  (105, 3, 'Mes ambitions d’accomplissement sont importants et élevés dans ma vie, je suis prêt(e) à faire ce qu’il faut pour mobiliser, en terme de temps, d’énergie et d’argent pour atteindre le succès auquel j’aspire vraiment.'),
  (106, 5, 'Je suis peu porté(e) par les implications dans les associations, amicales ou soirées diverses car je préfère me retrouver dans une réflexion tranquille plutôt que dans l’agitation émotionnelle collective.'),
  (107, 7, 'J’aime les environnements confortables et avec de l’allure, j’aime m’offrir des bonnes parties de shopping quand l’envie de me faire plaisir me prend.'),
  (108, 6, 'Je ressens souvent des sentiments contradictoires vis-à-vis des figures d’autorité, ce qui peut se traduire chez moi, par un retrait en cas d’insécurité, voire une attitude défensive ou provocante.'),
  (109, 1, 'Lorsque je vois certains détails qui ne me conviennent pas, je n’hésite pas à reprendre les autres (sans même qu’ils me le demandent), pour leur montrer comment accomplir leurs tâches correctement'),
  (110, 4, 'J’ai souvent l’impression de souffrir plus que les autres et d’être en contact avec de profondes émotions.'),
  (111, 7, 'Lorsque quelque chose me plaît vraiment, je me débrouille pour l’obtenir, car je ne vois pas de raison de manquer ou de passer à coté d’une opportunité.'),
  (112, 2, 'C’est important pour moi de soutenir les personnes qui en expriment le besoin et j’aime me sentir important(e) en répondant à leurs attentes.'),
  (113, 5, 'J’ai une tendance naturelle à garder mes projets pour moi et à ne pas les partager facilement aux personnes qui m’entourent. A moins qu’elles soient concernées par une partie de ce projet.'),
  (114, 8, 'Si quelqu’un n’a pas de valeur à mes yeux, il ne peut pas m’en donner.'),
  (115, 3, 'Tendre vers l’excellence est suffisamment important pour moi pour que j’y consacre mes pensées, mon temps et mon argent le plus régulièrement possible.'),
  (116, 6, 'J’ai tendance à être attentif(ve) voire soupçonneux(se) à l’égard des propositions qui pourraient davantage privilégier les bénéfices individuels que collectifs.'),
  (117, 9, 'J’aime ce qui est familier, la routine me convient pour autant qu’elle soit confortable et qu’elle préserve ma stabilité, voire ma tranquillité émotionnelle et mentale.'),
  (118, 6, 'Je suis de nature plutôt méfiant(e), je sens très vite si un danger ou une situation menaçante pourrait se présenter en terme de non respect de l’éthique.'),
  (119, 9, 'Quand différents points de vue me semblent intéressants, j’ai du mal à me donner des priorités et à m’engager rapidement sur des décisions précises, car justement, tous les points de vue sont intéressants.'),
  (120, 3, 'Même si j’ai parfois des baisses d’énergie (remise en cause, déception, pression), je peux montrer facilement aux autres que je reste mobilisé(e) et confiant(e) pour avancer vers l’atteinte de mes ou nos objectifs.'),
  (121, 4, 'Je peux facilement avoir tendance à la nostalgie en ravivant des sentiments du passé pour donner plus d’intensité ma vie présente.'),
  (122, 7, 'Enfant, je me préoccupais déjà plus de mes propres sources de stimulation que des problèmes des autres.'),
  (123, 1, 'Je peux être critique avec les autres s’ils m’apparaissent imprécis, inefficaces ou qu’ils n’avancent pas dans le cadre de la direction attendue.'),
  (124, 5, 'J’ai une tendance naturelle à cloisonner un peu ma vie (travail, famille, sports, loisirs,..), les personnes de ces différents domaines ne se connaissent pas entre-elles.'),
  (125, 8, 'Le courage et la force sont des atouts que je mobilise facilement, quand il s’agit de reprendre la main sur des situations qui ne me conviennent pas.'),
  (126, 2, 'Enfant, il était plus important pour moi de satisfaire les besoins des autres et de leur venir en aide.'),
  (127, 1, 'Les autres me reconnaissent facilement comme une personne organisée et précise, parfois même avec un coté un peu rigide voire coincée.'),
  (128, 8, 'Je suis suffisamment solide pour prendre une décision malgré le désaccord de mes proches'),
  (129, 9, 'J’ai souvent l’impression d’être à la fois surchargé(e) et impuissant(e) face à la multitude des tâches'),
  (130, 2, 'J’éprouve en général un grand désir d’apporter de l’assistance aux autres quel que soit le retour que j’en obtiens, car je sens qu’ainsi je tiens une place importante dans leur vie.'),
  (131, 4, 'J’aime être reconnu(e) comme un être à part, avec toute ma singularité, ma différence quitte même à surprendre mon entourage par mon originalité;'),
  (132, 3, 'Je sais très bien comment mettre en avant le meilleur de moi-même pour réussir dans les situations compliquées ou de pression, afin d’éviter de me laisser emporter par des sentiments d’échecs.'),
  (133, 5, 'Enfant, j’aimais me retrouver dans mon propre monde en me préservant de l’agitation de mes camarades'),
  (134, 7, 'J’aime dépasser certaines limites et aller au devant de certaines aventures, car je trouve ça plus stimulant et enivrant que de perdre son temps à ne rien faire.'),
  (135, 6, 'Je suis souvent félicité(e) ou honoré(e), par mes supérieurs ou ma hiérarchie pour mes capacités d’organisation, d’anticipation et de respect des règles engagées dans mes préparations')
on conflict (numero) do update set type = excluded.type, texte = excluded.texte;

-- Garde-fou : la migration echoue plutot que de laisser passer un
-- referentiel incomplet, parce qu'une cle fausse ne se voit jamais a l'oeil.
do $$
declare n int;
begin
  select count(*) into n from public.pm_items;
  if n <> 135 then raise exception 'referentiel incomplet : % items au lieu de 135', n; end if;

  select count(*) into n from (
    select type from public.pm_items group by type having count(*) <> 15
  ) t;
  if n <> 0 then raise exception '% type(s) n''ont pas 15 items', n; end if;
end $$;
